### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by alishefaee** [pasoonate/pasoonate-js#5]
متاسفانه 
node js
از دستور 
import
پشتیبانی نمیکند باید از دستور قدیمی تر 
require 
به جای آن استفاده کرد
```
H:\...\node_modules\pasoonate\src\Pasoonate.js:1
import Constants from './Constants';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (H:\pro\timenode\controller\calendarController.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
```

**Comment by ataiemajid63** [comment]
آدرس‌های زیر رو نگاه کنید، مقالاتی هستند که نشان می‌دهند که چگونه است ES6 در Nodejs استفاده کنید.

https://www.codementor.io/@iykyvic/writing-your-nodejs-apps-using-es6-6dh0edw2o
https://www.freecodecamp.org/news/how-to-enable-es6-and-beyond-syntax-with-node-and-express-68d3e11fe1ab/
https://dev.to/mukul_singhal/write-es6-in-node-using-babel-3m7p

موفق باشید

**Comment by alishefaee** [comment]
ضمن تشکر بابت کتابخانه ، من سعی کردم به دو روش پکیج را به ورژن قدیمی تر جاوااسکریپت تبدیل کنم
در روش اول به صورت دستی تمام دستورات رو به سینتکس قدیمی برگرداندم
در روش دوم همونطور که در مقاله ها اشاره شده از 
babel 
استفاده کردم
اما با فراخوانی متد
format()
ارور زیر ایجاد شد
```
(node:10476) Warning: Accessing non-existent property 'formatter' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
GET /today 500 74.023 ms - 1236
TypeError: Cannot read property 'setCalendar' of undefined
    at CalendarManager.format (H:\YoumePro\timenode\dist\src\calendar\/CalendarManager.js:119:20)
    at exports.today (H:\YoumePro\timenode\dist\controller\/calendarController.js:35:28)
    at Layer.handle [as handle_request] (H:\YoumePro\timenode\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\YoumePro\timenode\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\YoumePro\timenode\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (H:\YoumePro\timenode\node_modules\express\lib\router\layer.js:95:5)
    at H:\YoumePro\timenode\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (H:\YoumePro\timenode\node_modules\express\lib\router\index.js:335:12)
    at next (H:\YoumePro\timenode\node_modules\express\lib\router\index.js:275:10)
    at cors (H:\YoumePro\timenode\node_modules\cors\lib\index.js:188:7)
```
![Capture](https://user-images.githubusercontent.com/47412484/131260112-76f71083-4c9e-48c9-82b6-677e203a5bc6.JPG)
در صورت new issue  میسازم

**Comment by ataiemajid63** [comment]
با سلام
مشکل شما در نسخه 1.1.0 حل شده، لطفا نسخه جدید را نصب و استفاده نمایید.

با سپاس از صبر شما
